image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

branches:
  only:
    - master
    - develop

platform: Any CPU

install:
  - ps: .\dotnet-install.ps1 --version 2.0.0

configuration:
  - Release

build_script:
  - ps: .\scripts\BuildAndTest.ps1 -NoTest -NoPackage -NoPublish -NoSigningDirectory -Configuration Release

after_build:
  - ps: .\scripts\Run-Tests.ps1 -Configuration Release -AppVeyor

test: off

notifications:
  - provider: Email
    to:
     - v-lgold@microsoft.com
    subject: '{{projectName}} Build {{status}}: Version: {{buildVersion}}'
    on_build_status_changed: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
