name: Build and Test

on:
  pull_request:
    branches: [ '**' ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Build and Test
      shell: cmd
      run: call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && call BuildAndTest.cmd

    - name: Upload build artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: build-bin
        path: bld\bin
        if-no-files-found: error
